version: '3'

tasks:
  dev:
    aliases:
      - dev
    desc: 'run url shortener app with local config'
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml

  migrate:
    aliases:
      - migrate
    desc: 'up migrations'
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/url-shortener.db -migrations-path=./migrations